package com.mf.weatherapp.view_models.utils

class CountryCodes_ISO3166 {
    private val iso3166CountryCodes: Map<String, String> = mapOf(
        "Afghanistan" to "AF",
        "Albania" to "AL",
        "Algeria" to "DZ",
        "American Samoa" to "AS",
        "Andorra" to "AD",
        "Angola" to "AO",
        "Anguilla" to "AI",
        "Antarctica" to "AQ",
        "Antigua and Barbuda" to "AG",
        "Argentina" to "AR",
        "Armenia" to "AM",
        "Aruba" to "AW",
        "Australia" to "AU",
        "Austria" to "AT",
        "Azerbaijan" to "AZ",
        "Bahamas" to "BS",
        "Bahrain" to "BH",
        "Bangladesh" to "BD",
        "Barbados" to "BB",
        "Belarus" to "BY",
        "Belgium" to "BE",
        "Belize" to "BZ",
        "Benin" to "BJ",
        "Bermuda" to "BM",
        "Bhutan" to "BT",
        "Bolivia" to "BO",
        "Bosnia and Herzegovina" to "BA",
        "Botswana" to "BW",
        "Brazil" to "BR",
        "British Indian Ocean Territory" to "IO",
        "British Virgin Islands" to "VG",
        "Brunei" to "BN",
        "Bulgaria" to "BG",
        "Burkina Faso" to "BF",
        "Burundi" to "BI",
        "Cape Verde" to "CV",
        "Cambodia" to "KH",
        "Cameroon" to "CM",
        "Canada" to "CA",
        "Cayman Islands" to "KY",
        "Central African Republic" to "CF",
        "Chad" to "TD",
        "Chile" to "CL",
        "China" to "CN",
        "Christmas Island" to "CX",
        "Cocos (Keeling) Islands" to "CC",
        "Colombia" to "CO",
        "Comoros" to "KM",
        "Congo (Brazzaville)" to "CG",
        "Congo (Kinshasa)" to "CD",
        "Cook Islands" to "CK",
        "Costa Rica" to "CR",
        "Côte d'Ivoire" to "CI",
        "Croatia" to "HR",
        "Cuba" to "CU",
        "Curaçao" to "CW",
        "Cyprus" to "CY",
        "Czech Republic" to "CZ",
        "Denmark" to "DK",
        "Djibouti" to "DJ",
        "Dominica" to "DM",
        "Dominican Republic" to "DO",
        "Ecuador" to "EC",
        "Egypt" to "EG",
        "El Salvador" to "SV",
        "Equatorial Guinea" to "GQ",
        "Eritrea" to "ER",
        "Estonia" to "EE",
        "Ethiopia" to "ET",
        "Falkland Islands" to "FK",
        "Faroe Islands" to "FO",
        "Fiji" to "FJ",
        "Finland" to "FI",
        "France" to "FR",
        "French Guiana" to "GF",
        "French Polynesia" to "PF",
        "French Southern Territories" to "TF",
        "Gabon" to "GA",
        "Gambia" to "GM",
        "Georgia" to "GE",
        "Germany" to "DE",
        "Ghana" to "GH",
        "Gibraltar" to "GI",
        "Greece" to "GR",
        "Greenland" to "GL",
        "Grenada" to "GD",
        "Guadeloupe" to "GP",
        "Guam" to "GU",
        "Guatemala" to "GT",
        "Guernsey" to "GG",
        "Guinea" to "GN",
        "Guinea-Bissau" to "GW",
        "Guyana" to "GY",
        "Haiti" to "HT",
        "Honduras" to "HN",
        "Hong Kong" to "HK",
        "Hungary" to "HU",
        "Iceland" to "IS",
        "India" to "IN",
        "Indonesia" to "ID",
        "Iran" to "IR",
        "Iraq" to "IQ",
        "Ireland" to "IE",
        "Isle of Man" to "IM",
        "Israel" to "IL",
        "Italy" to "IT",
        "Jamaica" to "JM",
        "Japan" to "JP",
        "Jersey" to "JE",
        "Jordan" to "JO",
        "Kazakhstan" to "KZ",
        "Kenya" to "KE",
        "Kiribati" to "KI",
        "Korea (North)" to "KP",
        "Korea (South)" to "KR",
        "Kuwait" to "KW",
        "Kyrgyzstan" to "KG",
        "Laos" to "LA",
        "Latvia" to "LV",
        "Lebanon" to "LB",
        "Lesotho" to "LS",
        "Liberia" to "LR",
        "Libya" to "LY",
        "Liechtenstein" to "LI",
        "Lithuania" to "LT",
        "Luxembourg" to "LU",
        "Macao" to "MO",
        "Madagascar" to "MG",
        "Malawi" to "MW",
        "Malaysia" to "MY",
        "Maldives" to "MV",
        "Mali" to "ML",
        "Malta" to "MT",
        "Marshall Islands" to "MH",
        "Martinique" to "MQ",
        "Mauritania" to "MR",
        "Mauritius" to "MU",
        "Mayotte" to "YT",
        "Mexico" to "MX",
        "Micronesia" to "FM",
        "Moldova" to "MD",
        "Monaco" to "MC",
        "Mongolia" to "MN",
        "Montenegro" to "ME",
        "Montserrat" to "MS",
        "Morocco" to "MA",
        "Mozambique" to "MZ",
        "Myanmar" to "MM",
        "Namibia" to "NA",
        "Nauru" to "NR",
        "Nepal" to "NP",
        "Netherlands" to "NL",
        "New Caledonia" to "NC",
        "New Zealand" to "NZ",
        "Nicaragua" to "NI",
        "Niger" to "NE",
        "Nigeria" to "NG",
        "Niue" to "NU",
        "Norfolk Island" to "NF",
        "Northern Mariana Islands" to "MP",
        "Norway" to "NO",
        "Oman" to "OM",
        "Pakistan" to "PK",
        "Palau" to "PW",
        "Palestine" to "PS",
        "Panama" to "PA",
        "Papua New Guinea" to "PG",
        "Paraguay" to "PY",
        "Peru" to "PE",
        "Philippines" to "PH",
        "Pitcairn Islands" to "PN",
        "Poland" to "PL",
        "Portugal" to "PT",
        "Qatar" to "QA",
        "Réunion" to "RE",
        "Romania" to "RO",
        "Russia" to "RU",
        "Rwanda" to "RW",
        "Saint Kitts and Nevis" to "KN",
        "Saint Lucia" to "LC",
        "Saint Pierre and Miquelon" to "PM",
        "Saint Vincent and the Grenadines" to "VC",
        "Samoa" to "WS",
        "San Marino" to "SM",
        "Saudi Arabia" to "SA",
        "Senegal" to "SN",
        "Serbia" to "RS",
        "Seychelles" to "SC",
        "Sierra Leone" to "SL",
        "Singapore" to "SG",
        "Sint Maarten" to "SX",
        "Slovakia" to "SK",
        "Slovenia" to "SI",
        "Solomon Islands" to "SB",
        "Somalia" to "SO",
        "South Africa" to "ZA",
        "South Georgia & South Sandwich Islands" to "GS",
        "South Korea" to "KR",
        "South Sudan" to "SS",
        "Spain" to "ES",
        "Sri Lanka" to "LK",
        "Sudan" to "SD",
        "Suriname" to "SR",
        "Swaziland (Eswatini)" to "SZ",
        "Sweden" to "SE",
        "Switzerland" to "CH",
        "Syria" to "SY",
        "Taiwan" to "TW",
        "Tajikistan" to "TJ",
        "Tanzania" to "TZ",
        "Thailand" to "TH",
        "Timor-Leste" to "TL",
        "Togo" to "TG",
        "Tokelau" to "TK",
        "Tonga" to "TO",
        "Trinidad and Tobago" to "TT",
        "Tunisia" to "TN",
        "Turkey" to "TR",
        "Turkmenistan" to "TM",
        "Tuvalu" to "TV",
        "Uganda" to "UG",
        "Ukraine" to "UA",
        "United Arab Emirates" to "AE",
        "United Kingdom" to "GB",
        "United States" to "US",
        "Uruguay" to "UY",
        "Uzbekistan" to "UZ",
        "Vanuatu" to "VU",
        "Vatican City" to "VA",
        "Venezuela" to "VE",
        "Vietnam" to "VN",
        "Yemen" to "YE",
        "Zambia" to "ZM",
        "Zimbabwe" to "ZW"
    )
    fun getCountryCode( countryName: String): String?{
        return iso3166CountryCodes.entries.find { it.key == countryName}?.value
    }
}